"""Load, validate and seed the registry: sources, the function map, both lexicons.

Configuration is the input to almost every later stage, so it is validated once
here and a failure names the file and the field rather than surfacing three stages
later as a missing key (rule 4). `make up` runs this after the migrations.

Every file under `sources/` and `config/` is hashed rather than stored:
`config_versions` records which version of which file was applied and when, so a
run can be traced back to the phrases, thresholds and defaults that were in force.
The files themselves stay in YAML, which is the editable artifact.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import psycopg
import yaml
from pydantic import ValidationError

from monitor.db import connect
from monitor.models import Source

REPO = Path(__file__).resolve().parent.parent.parent
SOURCES_DIR = REPO / "sources"
CONFIG_DIR = REPO / "config"
FUNCTION_MAP = CONFIG_DIR / "function_map.yaml"
LEXICONS = {"en": CONFIG_DIR / "lexicon_en.yaml", "fr": CONFIG_DIR / "lexicon_fr.yaml"}
SYSTEM_NAMES = CONFIG_DIR / "system_names.yaml"

# Every config file that is version-hashed, and what kind of thing it is. Rule 6
# names all of these; a file added to config/ without a row here is a loud failure
# rather than a file that quietly stops being traceable.
CONFIG_KINDS = {
    "function_map.yaml": "function_map",
    "lexicon_en.yaml": "lexicon",
    "lexicon_fr.yaml": "lexicon",
    "thresholds.yaml": "thresholds",
    "record_defaults.yaml": "record_defaults",
    "system_names.yaml": "system_names",
    "review.yaml": "review",
    "fx.yaml": "fx",
}


class RegistryError(Exception):
    """A configuration file is wrong. The message names the file and the field."""


def _read_yaml(path: Path) -> dict:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise RegistryError(f"{path.name}: expected a mapping at the top level")
    return document


def load_sources(directory: Path = SOURCES_DIR) -> list[Source]:
    """Every sources/*.yaml, validated. Raises on a bad field or a duplicate id."""
    sources: list[Source] = []
    seen: dict[str, str] = {}

    for path in sorted(directory.glob("*.yaml")):
        document = _read_yaml(path)
        try:
            source = Source.model_validate(document)
        except ValidationError as error:
            fields = ", ".join(".".join(str(part) for part in item["loc"]) for item in error.errors())
            messages = "; ".join(item["msg"] for item in error.errors())
            raise RegistryError(f"{path.name}: invalid field(s) {fields}: {messages}") from error

        if source.id in seen:
            raise RegistryError(f"{path.name}: duplicate source id {source.id!r}, already in {seen[source.id]}")
        seen[source.id] = path.name
        sources.append(source)

    if not sources:
        raise RegistryError(f"{directory}: no source YAML found")
    return sources


def load_function_map(path: Path = FUNCTION_MAP) -> list[dict]:
    """The 33 functions. Generated by scripts/export_function_map.py, checked here."""
    functions = _read_yaml(path).get("functions")
    if not functions:
        raise RegistryError(f"{path.name}: no functions")

    seen = set()
    for function in functions:
        for field in ("function_id", "name", "pillar", "type_weight"):
            if field not in function:
                raise RegistryError(f"{path.name}: function {function.get('function_id', '?')} has no {field}")
        if function["function_id"] in seen:
            raise RegistryError(f"{path.name}: duplicate function_id {function['function_id']!r}")
        seen.add(function["function_id"])
    return functions


def load_system_names(path: Path = SYSTEM_NAMES) -> list[str]:
    """The system names that carry signal, in config order.

    One list, read by the translation client's acronym check, the translation
    system prompt and the scorer's prompt at step 6. Three copies of it in Python
    was the finding this replaced (rule 6).
    """
    names = _read_yaml(path).get("names")
    if not names:
        raise RegistryError(f"{path.name}: no names")
    if len(set(names)) != len(names):
        raise RegistryError(f"{path.name}: duplicate name in the list")
    return names


def load_lexicon(language: str, path: Path | None = None) -> tuple[dict[str, list[str]], str]:
    """Phrases by function_id, and the content hash that versions them."""
    path = path or LEXICONS[language]
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    functions = document.get("functions")
    if not functions:
        raise RegistryError(f"{path.name}: no functions")
    if document.get("language") != language:
        raise RegistryError(f"{path.name}: declares language {document.get('language')!r}, expected {language!r}")
    return functions, content_hash(path)


RECORD_DEFAULTS = CONFIG_DIR / "record_defaults.yaml"

# What `value_basis` may be. Owned here, at the config boundary, and imported by
# monitor/stage/record.py - not the other way round. The registry is the layer
# everything else reads config through; the first version of this loader reached
# forward into the stage layer for the constant and needed a deferred import to
# avoid the cycle, which was the dependency pointing the wrong way.
VALUE_BASES = frozenset({"published", "usd"})

# Every `sentences[...]` key monitor/stage/record.py reads. One list, checked on
# load, and pinned to record.py's actual reads by tests/unit/test_registry.py so
# a new sentence cannot be added to the code without being added here.
RECORD_SENTENCE_KEYS = frozenset(
    {
        "account_name_proposal",
        "eligibility_none_detected",
        "next_steps",
        "pricing_notes",
        "value_in_target",
        "value_no_usd",
        "value_not_stated",
        "value_usd_basis",
        "value_with_usd",
    }
)


def load_record_defaults(path: Path = RECORD_DEFAULTS) -> dict:
    """The record builder's config, validated where every other config file is (rule 4).

    Until 2026-09-12 this file was only content-hashed here and read directly by
    `monitor/stage/record.py`, which checks `value_basis` when it builds a record -
    so a typo in that key passed `make up` and surfaced when a reviewer opened a
    candidate page. Every other config kind fails on load; this one now does too,
    and review/decisions.py reads the file through this function rather than its
    own `yaml.safe_load`, so the check runs on the request path and not only in
    `make up`.
    """
    document = _read_yaml(path)
    basis = document.get("value_basis")
    if basis not in VALUE_BASES:
        raise RegistryError(f"{path.name}: value_basis is {basis!r}, must be one of {sorted(VALUE_BASES)}")
    sentences = document.get("sentences") or {}
    missing = RECORD_SENTENCE_KEYS - set(sentences)
    if missing:
        raise RegistryError(f"{path.name}: sentences is missing {sorted(missing)}; the record builder renders them")
    if not document.get("columns"):
        raise RegistryError(f"{path.name}: no columns; appendix E's export has nothing to write")
    return document


def config_files(sources_dir: Path = SOURCES_DIR, config_dir: Path = CONFIG_DIR) -> list[tuple[Path, str, str | None]]:
    """Every hashed file as (path, kind, language). Language is set for lexicons only.

    The directories are arguments for the same reason `load_sources` takes one: a
    test that wants to see what happens to a stray file points this at a copy
    rather than writing into the real config directory and relying on cleanup.
    """
    files: list[tuple[Path, str, str | None]] = [(path, "source", None) for path in sorted(sources_dir.glob("*.yaml"))]

    for path in sorted(config_dir.glob("*.yaml")):
        kind = CONFIG_KINDS.get(path.name)
        if kind is None:
            raise RegistryError(f"{path.name}: no kind in CONFIG_KINDS, so it would not be version-hashed (rule 6)")
        language = path.stem.removeprefix("lexicon_") if kind == "lexicon" else None
        files.append((path, kind, language))

    return files


def content_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def record_config_versions(conn: psycopg.Connection) -> int:
    """One row per config file per content hash. Re-seeding the same files is a no-op."""
    for path, kind, language in config_files():
        digest = content_hash(path)
        conn.execute(
            """
            insert into config_versions (version, path, kind, language, content_hash)
            values (%s, %s, %s, %s, %s)
            on conflict (path, content_hash) do nothing
            """,
            (
                f"{path.stem}-{digest[:12]}",
                str(path.relative_to(REPO)),
                kind,
                language,
                digest,
            ),
        )
    return len(config_files())


def seed(conn: psycopg.Connection) -> dict[str, int]:
    """Upsert the registry into the database. One transaction, all or nothing."""
    sources = load_sources()
    functions = load_function_map()
    # Not written to the database - the builder reads the file - but validated here
    # so `make up` fails on a bad value_basis instead of the first candidate page.
    load_record_defaults()

    with conn.transaction():
        for source in sources:
            conn.execute(
                """
                insert into sources (id, name, country, admin_level, language, stream, access_type,
                                     connector_class, wave, tos_status, enabled, expected_min,
                                     expected_max, max_consecutive_failures)
                values (%(id)s, %(name)s, %(country)s, %(admin_level)s, %(language)s, %(stream)s,
                        %(access_type)s, %(connector_class)s, %(wave)s, %(tos_status)s, %(enabled)s,
                        %(expected_min)s, %(expected_max)s, %(max_consecutive_failures)s)
                on conflict (id) do update set
                    name = excluded.name, country = excluded.country,
                    admin_level = excluded.admin_level, language = excluded.language,
                    stream = excluded.stream, access_type = excluded.access_type,
                    connector_class = excluded.connector_class, wave = excluded.wave,
                    tos_status = excluded.tos_status, enabled = excluded.enabled,
                    expected_min = excluded.expected_min, expected_max = excluded.expected_max,
                    max_consecutive_failures = excluded.max_consecutive_failures
                """,
                source.model_dump(
                    include={
                        "id",
                        "name",
                        "country",
                        "admin_level",
                        "language",
                        "stream",
                        "access_type",
                        "connector_class",
                        "wave",
                        "tos_status",
                        "enabled",
                        "expected_min",
                        "expected_max",
                        "max_consecutive_failures",
                    }
                ),
            )

        lexicons = {language: load_lexicon(language) for language in LEXICONS}

        for function in functions:
            conn.execute(
                """
                insert into function_map (function_id, name, pillar, type_weight, keywords_en, keywords_fr)
                values (%s, %s, %s, %s, %s, %s)
                on conflict (function_id) do update set
                    name = excluded.name, pillar = excluded.pillar,
                    type_weight = excluded.type_weight,
                    keywords_en = excluded.keywords_en, keywords_fr = excluded.keywords_fr
                """,
                (
                    function["function_id"],
                    function["name"],
                    function["pillar"],
                    function["type_weight"],
                    lexicons["en"][0].get(function["function_id"], []),
                    lexicons["fr"][0].get(function["function_id"], []),
                ),
            )

        versioned = record_config_versions(conn)

    return {"sources": len(sources), "functions": len(functions), "config_files": versioned}


def main() -> int:
    with connect("pipeline") as conn:
        counts = seed(conn)
    print(
        f"registry: {counts['sources']} sources, {counts['functions']} functions, "
        f"{counts['config_files']} config files version-hashed"
    )
    return 0
