"""Load, validate and seed the registry: sources, the function map, both lexicons.

Configuration is the input to almost every later stage, so it is validated once
here and a failure names the file and the field rather than surfacing three stages
later as a missing key (rule 4). `make up` runs this after the migrations.

The lexicons are hashed rather than stored: `lexicon_versions` records which
version of which language was applied and when, so a scoring run can be traced
back to the phrases that were in force. The phrases themselves stay in the YAML,
which is the editable artifact.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import psycopg
import yaml
from pydantic import ValidationError

from monitor.db import connect
from monitor.models import Source

REPO = Path(__file__).resolve().parent.parent.parent
SOURCES_DIR = REPO / "sources"
CONFIG_DIR = REPO / "config"
FUNCTION_MAP = CONFIG_DIR / "function_map.yaml"
LEXICONS = {"en": CONFIG_DIR / "lexicon_en.yaml", "fr": CONFIG_DIR / "lexicon_fr.yaml"}


class RegistryError(Exception):
    """A configuration file is wrong. The message names the file and the field."""


def _read_yaml(path: Path) -> dict:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise RegistryError(f"{path.name}: expected a mapping at the top level")
    return document


def load_sources(directory: Path = SOURCES_DIR) -> list[Source]:
    """Every sources/*.yaml, validated. Raises on a bad field or a duplicate id."""
    sources: list[Source] = []
    seen: dict[str, str] = {}

    for path in sorted(directory.glob("*.yaml")):
        document = _read_yaml(path)
        try:
            source = Source.model_validate(document)
        except ValidationError as error:
            fields = ", ".join(".".join(str(part) for part in item["loc"]) for item in error.errors())
            messages = "; ".join(item["msg"] for item in error.errors())
            raise RegistryError(f"{path.name}: invalid field(s) {fields}: {messages}") from error

        if source.id in seen:
            raise RegistryError(f"{path.name}: duplicate source id {source.id!r}, already in {seen[source.id]}")
        seen[source.id] = path.name
        sources.append(source)

    if not sources:
        raise RegistryError(f"{directory}: no source YAML found")
    return sources


def load_function_map(path: Path = FUNCTION_MAP) -> list[dict]:
    """The 33 functions. Generated by scripts/export_function_map.py, checked here."""
    functions = _read_yaml(path).get("functions")
    if not functions:
        raise RegistryError(f"{path.name}: no functions")

    seen = set()
    for function in functions:
        for field in ("function_id", "name", "pillar", "type_weight"):
            if field not in function:
                raise RegistryError(f"{path.name}: function {function.get('function_id', '?')} has no {field}")
        if function["function_id"] in seen:
            raise RegistryError(f"{path.name}: duplicate function_id {function['function_id']!r}")
        seen.add(function["function_id"])
    return functions


def load_lexicon(language: str, path: Path | None = None) -> tuple[dict[str, list[str]], str]:
    """Phrases by function_id, and the content hash that versions them."""
    path = path or LEXICONS[language]
    raw = path.read_text(encoding="utf-8")
    document = yaml.safe_load(raw)
    functions = document.get("functions")
    if not functions:
        raise RegistryError(f"{path.name}: no functions")
    if document.get("language") != language:
        raise RegistryError(f"{path.name}: declares language {document.get('language')!r}, expected {language!r}")
    return functions, hashlib.sha256(raw.encode("utf-8")).hexdigest()


def seed(conn: psycopg.Connection) -> dict[str, int]:
    """Upsert the registry into the database. One transaction, all or nothing."""
    sources = load_sources()
    functions = load_function_map()

    with conn.transaction():
        for source in sources:
            conn.execute(
                """
                insert into sources (id, name, country, admin_level, language, stream, access_type,
                                     connector_class, wave, tos_status, enabled, expected_min,
                                     expected_max, max_consecutive_failures)
                values (%(id)s, %(name)s, %(country)s, %(admin_level)s, %(language)s, %(stream)s,
                        %(access_type)s, %(connector_class)s, %(wave)s, %(tos_status)s, %(enabled)s,
                        %(expected_min)s, %(expected_max)s, %(max_consecutive_failures)s)
                on conflict (id) do update set
                    name = excluded.name, country = excluded.country,
                    admin_level = excluded.admin_level, language = excluded.language,
                    stream = excluded.stream, access_type = excluded.access_type,
                    connector_class = excluded.connector_class, wave = excluded.wave,
                    tos_status = excluded.tos_status, enabled = excluded.enabled,
                    expected_min = excluded.expected_min, expected_max = excluded.expected_max,
                    max_consecutive_failures = excluded.max_consecutive_failures
                """,
                source.model_dump(
                    include={
                        "id",
                        "name",
                        "country",
                        "admin_level",
                        "language",
                        "stream",
                        "access_type",
                        "connector_class",
                        "wave",
                        "tos_status",
                        "enabled",
                        "expected_min",
                        "expected_max",
                        "max_consecutive_failures",
                    }
                ),
            )

        lexicons = {language: load_lexicon(language) for language in LEXICONS}

        for function in functions:
            conn.execute(
                """
                insert into function_map (function_id, name, pillar, type_weight, keywords_en, keywords_fr)
                values (%s, %s, %s, %s, %s, %s)
                on conflict (function_id) do update set
                    name = excluded.name, pillar = excluded.pillar,
                    type_weight = excluded.type_weight,
                    keywords_en = excluded.keywords_en, keywords_fr = excluded.keywords_fr
                """,
                (
                    function["function_id"],
                    function["name"],
                    function["pillar"],
                    function["type_weight"],
                    lexicons["en"][0].get(function["function_id"], []),
                    lexicons["fr"][0].get(function["function_id"], []),
                ),
            )

        for language, (_, content_hash) in lexicons.items():
            conn.execute(
                """
                insert into lexicon_versions (version, language, content_hash)
                values (%s, %s, %s)
                on conflict (version) do nothing
                """,
                (f"{language}-{content_hash[:12]}", language, content_hash),
            )

    return {"sources": len(sources), "functions": len(functions), "lexicons": len(LEXICONS)}


def main() -> int:
    with connect("pipeline") as conn:
        counts = seed(conn)
    print(
        f"registry: {counts['sources']} sources, {counts['functions']} functions, "
        f"{counts['lexicons']} lexicon versions"
    )
    return 0
